services:
  inventory:
    build: 
      context: .
      dockerfile: ./apps/inventory/Dockerfile
      target: development
    command: npm run start:dev inventory
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app