apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
  name: cart-tcp
spec:
  ports:
  - name: "tcp"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: cart
  type: ClusterIP
