apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
  name: cart-http
spec:
  ports:
  - name: "http"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: cart
  type: NodePort
