apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - image: vietdinh1801/ecommerce-microservices-nestjs-app-inventory:production
        name: inventory
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: connectionString
        - name: CLOUDINARY_NAME
          value: 'dnv2v2tiz'
        - name: CLOUDINARY_API_KEY
          value: '335363687126965'
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudinary
              key: secretKey
        - name: HTTP_PORT
          value: '3000'
        - name: TCP_PORT
          value: '3005'
        - name: AUTH_HOST
          value: auth-tcp
        - name: AUTH_PORT
          value: '3002'
        ports:
          - containerPort: 3000
          - containerPort: 3005
