apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory
  name: inventory-http
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: inventory
  type: NodePort

